
package ilac_takip;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

/**
 *
 * @author Oğuz Kaan Satan
 */
public class ilac_ekle extends javax.swing.JFrame {
  
    /**
     * Creates new form ilac_ekle
     */ // int ilac_no,String adi,String turu,int kullanim_sayisi,int doz,String skt,int kalanGun
 
//   static ArrayList<ilac> ilaclar = new ArrayList();
           
    
 DefaultComboBoxModel dcm2= new DefaultComboBoxModel();
 
 
 EntityManagerFactory emf= Persistence.createEntityManagerFactory("ilac_takip_denemePU");
 EntityManager em=emf.createEntityManager();
    List<Ilac> ilaclar;
    List<Tur> turler;
    
 
    public ilac_ekle() {
        Query q=em.createQuery("SELECT i FROM Ilac i");
        ilaclar=q.getResultList();
        q=em.createQuery("SELECT t FROM Tur t");
        turler=q.getResultList();
        
        
        initComponents();
        for (Tur tur : turler) {
            cbTur.addItem(tur);
        }
       
 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        txt_adi = new javax.swing.JTextField();
        txt_kullanım_sayisi = new javax.swing.JTextField();
        txt_doz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_ilac_ekle = new javax.swing.JButton();
        txt_ilac_no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_kalanGun = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        combo_skt_gun = new javax.swing.JComboBox();
        combo_skt_ay = new javax.swing.JComboBox();
        combo_skt_sene = new javax.swing.JComboBox();
        cbTur = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_kullanım_sayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kullanım_sayisiActionPerformed(evt);
            }
        });

        jLabel1.setText("İlaç Adı :");

        jLabel2.setText("İlaç Türü :");

        jLabel3.setText("Kullanım Sayısı :");

        jLabel4.setText("Doz :");

        jLabel5.setText("Son Kullanma Tarihi :");

        btn_ilac_ekle.setText("İlaç Ekle");
        btn_ilac_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilac_ekleActionPerformed(evt);
            }
        });

        jLabel6.setText("İlaç No :");

        jLabel7.setText("Bir sayı giriniz");

        jLabel8.setText("Bir metin giriniz");

        jLabel9.setText("Bir metin giriniz");

        jLabel10.setText("Bir sayı giriniz");

        jLabel11.setText("Bir sayı giriniz");

        txt_kalanGun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kalanGunActionPerformed(evt);
            }
        });

        jLabel13.setText("Kalan Gün :");

        jLabel14.setText("Bir sayı giriniz");

        combo_skt_gun.setMaximumRowCount(30);
        combo_skt_gun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        combo_skt_gun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_skt_gunActionPerformed(evt);
            }
        });

        combo_skt_ay.setMaximumRowCount(30);
        combo_skt_ay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        combo_skt_ay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_skt_ayActionPerformed(evt);
            }
        });

        combo_skt_sene.setMaximumRowCount(30);
        combo_skt_sene.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023" }));
        combo_skt_sene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_skt_seneActionPerformed(evt);
            }
        });

        cbTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_ilac_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_doz, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_kullanım_sayisi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_kalanGun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_skt_gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_skt_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_adi)
                            .addComponent(txt_ilac_no)
                            .addComponent(cbTur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(combo_skt_sene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ilac_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(cbTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullanım_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_doz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kalanGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_skt_gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_skt_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_skt_sene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addComponent(btn_ilac_ekle)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ilac_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilac_ekleActionPerformed
        // TODO add your handling code here:
        boolean ayniMi = true; // isThisUnique
        for (Ilac object : ilaclar) {
            if (object.getId() == Integer.parseInt(txt_ilac_no.getText())) { // Bu ilaç daha önce oluşturulmuş mu? == Bu ID daha önce oluşturulmuş mu?
                ayniMi = false;
                break;
            }
        }
       
        if (ayniMi) { // isThisUnique == True

            try {
                String tarih=(combo_skt_gun.getSelectedItem()+"."+ combo_skt_ay.getSelectedItem()+"."+combo_skt_sene.getSelectedItem());
                Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                String insert="INSERT INTO ILAC (ID,AD,SKT,DOZ,KS,KALANGUN,TUR) VALUES (?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(insert);
                ps.setInt(1,Integer.parseInt(txt_ilac_no.getText()));
                ps.setString(2,(txt_adi.getText()));
                ps.setString(3,tarih);
                ps.setInt(4,Integer.parseInt(txt_doz.getText()));
                ps.setInt(5,Integer.parseInt(txt_kullanım_sayisi.getText()));
                ps.setInt(6,Integer.parseInt(txt_kalanGun.getText()));
                ps.setInt(7,((Tur)cbTur.getSelectedItem()).getTurid());
                ps.executeUpdate();
                con.commit();
                con.close();
                int tur=((Tur)cbTur.getSelectedItem()).getTurid();
                
                  File file = new File("ilaclar.txt");
            if(!file.exists()){
                Files.createFile(file.toPath()); 
            }
           
            FileWriter fw=new FileWriter(file.toString());
            BufferedWriter bw=new BufferedWriter(fw);

                       for (Ilac i : ilaclar) {
                    bw.write(i.getId()+"-"+i.getAd()+"-"+i.getTur()+"\n");
                }
                        bw.write(txt_ilac_no.getText()+"-"+txt_adi.getText()+"-"+String.valueOf(tur));
                        bw.close();
                        
                ilac_takip_anasayfa i = new ilac_takip_anasayfa();
                i.setVisible(true);
                this.setVisible(false);
                

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Girdiginiz değerleri kontrol ediniz", "Hata", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(ilac_ekle.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ilac_ekle.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Bu ID ye sahip bir ilac var");
        }


    }//GEN-LAST:event_btn_ilac_ekleActionPerformed
    private void txt_kullanım_sayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kullanım_sayisiActionPerformed
        // TDO add your handling code here:
    }//GEN-LAST:event_txt_kullanım_sayisiActionPerformed

    private void txt_kalanGunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kalanGunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kalanGunActionPerformed

    private void combo_skt_gunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_skt_gunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_skt_gunActionPerformed

    private void combo_skt_ayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_skt_ayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_skt_ayActionPerformed

    private void combo_skt_seneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_skt_seneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_skt_seneActionPerformed

    private void cbTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ilac_ekle;
    private javax.swing.JComboBox cbTur;
    private javax.swing.JComboBox combo_skt_ay;
    private javax.swing.JComboBox combo_skt_gun;
    private javax.swing.JComboBox combo_skt_sene;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_doz;
    private javax.swing.JTextField txt_ilac_no;
    private javax.swing.JTextField txt_kalanGun;
    private javax.swing.JTextField txt_kullanım_sayisi;
    // End of variables declaration//GEN-END:variables
}
