package ilac_takip;

import static ilac_takip.Ilac_.tur;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oğuz Kaan Satan
 */
public class ilac_takip_anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form ilac_takip_anasayfa
     */
    static DefaultTableModel dtm = new DefaultTableModel();

    List<Ilac> ilaclar;
    List<Tur> turler;

    void getList() {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ilac_takip_denemePU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select i from Ilac i"); //"jdbc:derby://localhost:1527/sample [app on APP]"
        ilaclar = q.getResultList();
        q = em.createQuery("SELECT t FROM Tur t");
        turler = q.getResultList();
    }

    public ilac_takip_anasayfa() {
        initComponents();

        getList();

        System.out.println(ilaclar);

        dtm.setColumnIdentifiers(new String[]{"İlaç No", "İlaç Adı", "Türü", "Kullanım Sayısı", "Doz", "SKT", "Kalan Gün"});
        dtm.setRowCount(0);
        tbl_kullanılan_ilaclar.setModel(dtm);
        for (int i = 0; i < ilaclar.size(); i++) {
            String tur = "";
            for (int j = 0; j < turler.size(); j++) {
                if (ilaclar.get(i).getTur() == turler.get(j).getTurid()) {
                    tur = turler.get(j).getAd();
                }
            }
            dtm.addRow(new Object[]{ilaclar.get(i).getId(), ilaclar.get(i).getAd(), tur, ilaclar.get(i).getKs(), ilaclar.get(i).getDoz(),
                ilaclar.get(i).getSkt(), ilaclar.get(i).getKalangun()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kullanılan_ilaclar = new javax.swing.JTable();
        btn_ilac_ekle_menu = new javax.swing.JButton();
        btn_ilac_sil = new javax.swing.JButton();
        txt_ilac_ara = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_arama_sonuc = new javax.swing.JList<String>();
        btn_ilac_ara = new javax.swing.JButton();
        cb_arama = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        btn_ilac_degistir = new javax.swing.JButton();
        sonrakiGun = new javax.swing.JButton();
        btn_tumunuSil = new javax.swing.JButton();

        button1.setLabel("button1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_kullanılan_ilaclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_kullanılan_ilaclar);

        btn_ilac_ekle_menu.setText("İlaç ekle");
        btn_ilac_ekle_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilac_ekle_menuActionPerformed(evt);
            }
        });

        btn_ilac_sil.setText("İlaç sil");
        btn_ilac_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilac_silActionPerformed(evt);
            }
        });

        txt_ilac_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ilac_araActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lst_arama_sonuc);

        btn_ilac_ara.setText("İlac Ara");
        btn_ilac_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilac_araActionPerformed(evt);
            }
        });

        cb_arama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İlac No", "İlac Adı" }));
        cb_arama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_aramaİtemStateChanged(evt);
            }
        });
        cb_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_aramaActionPerformed(evt);
            }
        });

        jButton1.setText("ÇIKIŞ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_ilac_degistir.setText("İilaç bilgisi değiştir");
        btn_ilac_degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ilac_degistirActionPerformed(evt);
            }
        });

        sonrakiGun.setText("Sonraki Gün");
        sonrakiGun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakiGunActionPerformed(evt);
            }
        });

        btn_tumunuSil.setText("Tümünü Sil");
        btn_tumunuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumunuSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_ilac_ekle_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ilac_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_tumunuSil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_ilac_degistir)
                                .addGap(18, 18, 18)
                                .addComponent(sonrakiGun, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ilac_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_ilac_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_ilac_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_arama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_ilac_ara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonrakiGun)
                    .addComponent(btn_ilac_degistir)
                    .addComponent(btn_ilac_sil)
                    .addComponent(btn_ilac_ekle_menu)
                    .addComponent(btn_tumunuSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ilac_ekle_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilac_ekle_menuActionPerformed
        // TODO add your handling code here:

        ilac_ekle ekran = new ilac_ekle();
        ekran.setVisible(true);
        this.setVisible(false);
        ekran.setDefaultCloseOperation(WIDTH);

    }//GEN-LAST:event_btn_ilac_ekle_menuActionPerformed

    private void btn_ilac_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilac_silActionPerformed
        // TODO add your handling code here:
        getList();
        if (tbl_kullanılan_ilaclar.getSelectedRow() != -1) {

            int selectedRowIndex = tbl_kullanılan_ilaclar.getSelectedRow();
            dtm.removeRow(selectedRowIndex);
            try {
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                String sqlUpdate = "DELETE FROM ILAC WHERE ID=(?)";
                PreparedStatement ps = con.prepareStatement(sqlUpdate);
                ps.setInt(1, ilaclar.get(selectedRowIndex).getId());
                ps.executeUpdate();
                con.commit();
                con.close();
                
                
                File file = new File("ilaclar.txt");
                if (!file.exists()) {
                    Files.createFile(file.toPath());
                }

       
                FileWriter fw = new FileWriter(file.toString());
                BufferedWriter bw = new BufferedWriter(fw);
                
                getList();
                
                for (Ilac i : ilaclar) {
                    bw.write(i.getId() + "-" + i.getAd() + "-" + i.getTur() + "\n");
                }
               
                bw.close();

            }catch(IOException e){
                
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                ex.printStackTrace();
                Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
          

        }

    }//GEN-LAST:event_btn_ilac_silActionPerformed

    private void btn_ilac_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilac_araActionPerformed
        // TODO add your handling code here:
        getList();

        try {
            DefaultListModel dlm = new DefaultListModel();
            lst_arama_sonuc.removeAll();
            lst_arama_sonuc.setModel(dlm);
            
            Path p = Paths.get("ilaclar.txt");
            FileReader fr = new FileReader(p.toFile());
            String line;
            BufferedReader br = new BufferedReader(fr);
            while ((line = br.readLine()) != null) {
                String[] arr = line.split("-");
                if (cb_arama.getSelectedIndex() == 0) {
                    if (Integer.parseInt(arr[0]) == Integer.parseInt(txt_ilac_ara.getText())) {
                        String tur = "";
                        for (int j = 0; j < turler.size(); j++) {
                            if (Integer.valueOf(arr[2]) == turler.get(j).getTurid()) {
                                tur = turler.get(j).getAd();
                            }
                        }
                        dlm.addElement(arr[0] + " " + arr[1] + " " + tur); 

                    }
                    lst_arama_sonuc.setModel(dlm);
                } else {
                   if (arr[1].equals(txt_ilac_ara.getText())) {
                        String tur = "";
                        for (int j = 0; j < turler.size(); j++) {
                            if (Integer.valueOf(arr[2]) == turler.get(j).getTurid()) {
                                tur = turler.get(j).getAd();
                            }
                        }
                        dlm.addElement(arr[0] + " " + arr[1] + " " + tur); 

                    }
                    lst_arama_sonuc.setModel(dlm);
                }
            }
            br.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "gecersiz deger girdiniz!", "Hata", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_ilac_araActionPerformed

    private void cb_aramaİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_aramaİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_aramaİtemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        kullanici_ekrani ekrani = new kullanici_ekrani();
        ekrani.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ilac_degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ilac_degistirActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tbl_kullanılan_ilaclar.getSelectedRow();

        if (tbl_kullanılan_ilaclar.getSelectedRow() != -1) {
            try {
                dtm.insertRow(selectedRowIndex, new Object[]{dtm.getValueAt(selectedRowIndex, 0), dtm.getValueAt(selectedRowIndex, 1),
                    dtm.getValueAt(selectedRowIndex, 2), dtm.getValueAt(selectedRowIndex, 3),
                    dtm.getValueAt(selectedRowIndex, 4), dtm.getValueAt(selectedRowIndex, 5), dtm.getValueAt(selectedRowIndex, 6)});

                dtm.removeRow(selectedRowIndex + 1);

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                String sqlUpdate = "UPDATE ILAC SET AD = (?),TUR=(?),KS=(?),DOZ=(?),SKT=(?),KALANGUN=(?) WHERE ID=(?) ";
                PreparedStatement ps = con.prepareStatement(sqlUpdate);
                
                ps.setString(1, dtm.getValueAt(selectedRowIndex, 1).toString());
                int tur=0;
                for (int i = 0; i < turler.size(); i++) {
                    if (dtm.getValueAt(selectedRowIndex, 2).toString().equals(turler.get(i).getAd())) {
                        tur=turler.get(i).getTurid();
                    }
                }
                ps.setInt(2,tur);
                ps.setInt(3, Integer.valueOf(dtm.getValueAt(selectedRowIndex, 3).toString()));
                ps.setInt(4, Integer.valueOf(dtm.getValueAt(selectedRowIndex, 4).toString()));
                ps.setString(5, dtm.getValueAt(selectedRowIndex, 5).toString());
                ps.setInt(6, Integer.valueOf(dtm.getValueAt(selectedRowIndex, 6).toString()));
                ps.setInt(7, Integer.valueOf(dtm.getValueAt(selectedRowIndex, 0).toString()));

                ps.executeUpdate();
                con.commit();
                con.close();
                
                getList();

            } catch (ClassCastException e) {
                JOptionPane.showMessageDialog(this, "lütfen parametreleri kontrol ediniz (ilaç  no değiştirilemez)");

            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(this, "lütfen parametreleri kontrol ediniz");
            } catch (SQLException ex) {
                Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btn_ilac_degistirActionPerformed

    private void sonrakiGunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonrakiGunActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < ilaclar.size(); i++) {
            if (ilaclar.get(i).getKalangun() > 0) {
                try {
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                    String sqlUpdate = "UPDATE ILAC SET KALANGUN=(?) WHERE ID=(?)";
                    PreparedStatement ps = con.prepareStatement(sqlUpdate);
                    ps.setInt(1, ilaclar.get(i).getKalangun() - 1);
                    ps.setInt(2, ilaclar.get(i).getId());
                    ps.executeUpdate();
                    con.commit();
                    con.close();
                    dtm.setValueAt(ilaclar.get(i).getKalangun() - 1, i, 6);
                    ilaclar.get(i).setKalangun(ilaclar.get(i).getKalangun() - 1);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }

            }

        }


    }//GEN-LAST:event_sonrakiGunActionPerformed

    private void cb_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_aramaActionPerformed

    private void txt_ilac_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ilac_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ilac_araActionPerformed

    private void btn_tumunuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumunuSilActionPerformed
        // TODO add your handling code here:

        while (dtm.getRowCount() > 0) {

            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
            }
    }//GEN-LAST:event_btn_tumunuSilActionPerformed

        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            String sqlUpdate = "DELETE FROM ILAC ";
            PreparedStatement ps = con.prepareStatement(sqlUpdate);
            ps.executeUpdate();
            con.commit();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ilac_takip_anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ilac_takip_anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ilac_ara;
    private javax.swing.JButton btn_ilac_degistir;
    private javax.swing.JButton btn_ilac_ekle_menu;
    private javax.swing.JButton btn_ilac_sil;
    private javax.swing.JButton btn_tumunuSil;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> cb_arama;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> lst_arama_sonuc;
    private javax.swing.JButton sonrakiGun;
    private javax.swing.JTable tbl_kullanılan_ilaclar;
    private javax.swing.JTextField txt_ilac_ara;
    // End of variables declaration//GEN-END:variables
}
