
package ilac_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import sun.net.www.content.audio.x_aiff;

/**
 *
 * @author Oğuz Kaan Satan
 */
public class kullanici_ekrani extends javax.swing.JFrame {

    // static String userName = "oguz";
    //static String password = "1234";
    /**
     * 
     */
    //ArrayList<Kullanici> kullanicilar=new ArrayList<>( Arrays.asList(new Kullanici("admin","admin")) );
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ilac_takip_denemePU");
    EntityManager em = emf.createEntityManager(); 
    Query q = em.createQuery("SELECT k FROM Kullanici k");
    List<Kullanici> kullanicilar ;
    
    public kullanici_ekrani() {
    kullanicilar=q.getResultList();
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psw_kullanici_parola = new javax.swing.JPasswordField();
        txt_kullanici_adi = new javax.swing.JTextField();
        btn_kullanici_giris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_kullanici_kayıt_ol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_kullanici_giris.setText("Giriş");
        btn_kullanici_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullanici_girisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kullanıcı Girişi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kullanıcı adı");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Parola");

        btn_kullanici_kayıt_ol.setText("Kayıt Ol");
        btn_kullanici_kayıt_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullanici_kayıt_olActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_kullanici_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_kullanici_kayıt_ol))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(psw_kullanici_parola, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_kullanici_adi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psw_kullanici_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kullanici_giris)
                    .addComponent(btn_kullanici_kayıt_ol))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//if(txt_kullanici_adi.getText().equals(userName) && String.valueOf(psw_kullanici_parola.getPassword()).equals(password))
    private void btn_kullanici_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullanici_girisActionPerformed
       kullanicilar=q.getResultList();
       
        boolean varMi = false;
        String x=String.valueOf(psw_kullanici_parola.getPassword()); // kutuya girilen şifreyi al (kısaltma)
        
        for (Kullanici k : kullanicilar) { // kullanicilar = { "Oguz", "Mert", "Saban", "Sait"} -> 
            
            // Kullanici adi ve sifre dogru ise buraya girer
            if (txt_kullanici_adi.getText().equals(k.getAd())&& x.equals(k.getParola())) { // kullanici adi dogru mu && parola dogru mu
                varMi = true; // "sait".equals(Oguz.kullanici_adi)
               

                  //  JOptionPane.showMessageDialog(this, "aaaaa", "Hata", JOptionPane.ERROR_MESSAGE);
                    ilac_takip_anasayfa ana1 = new ilac_takip_anasayfa();
                    ana1.setVisible(true);
                    this.setVisible(false);

                
                
            }
        } // for'un bitişi
        if( varMi==false){
        JOptionPane.showMessageDialog(this, "Kullanıcı Adı veya Şifre Hatalı.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
        
        
      
        
    }//GEN-LAST:event_btn_kullanici_girisActionPerformed

    private void btn_kullanici_kayıt_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullanici_kayıt_olActionPerformed
        // TODO add your handling code here:
        kullanicilar=q.getResultList();
        
        boolean varMi = true;
        for (Kullanici k : kullanicilar) {
            if (txt_kullanici_adi.getText().equals(k.getAd())) {
                varMi = false;
                JOptionPane.showMessageDialog(this, "Böyle bir kullanıcı zaten var.", "Hata", JOptionPane.ERROR_MESSAGE);
            }

        }
        if (txt_kullanici_adi.getText().equals("") || String.valueOf(psw_kullanici_parola.getText()).equals("") && 
                txt_kullanici_adi.getText().equals(" ") || String.valueOf(psw_kullanici_parola.getText()).equals(" ")) { // İkisinden biri boşsa
           JOptionPane.showMessageDialog(this, "Kullanıcı adı ve Parola Kısmını Doldurunuz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
        
        else { //İkisi de dolu ise
            if (varMi) {
                try {
                    Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                    String insert="INSERT INTO KULLANICI (AD,PAROLA) VALUES (?,?)";
                    PreparedStatement ps=con.prepareStatement(insert);
                    ps.setString(1,txt_kullanici_adi.getText() );
                    ps.setString(2,psw_kullanici_parola.getText() );
                    ps.executeUpdate();
                    con.commit();
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(kullanici_ekrani.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
            }
        }
        
    }//GEN-LAST:event_btn_kullanici_kayıt_olActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanici_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanici_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanici_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanici_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanici_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kullanici_giris;
    private javax.swing.JButton btn_kullanici_kayıt_ol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField psw_kullanici_parola;
    private javax.swing.JTextField txt_kullanici_adi;
    // End of variables declaration//GEN-END:variables
}
